backend:
  name: github
  branch: main
  repo: Noor-Arsenal/Arsenal-academy
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
    - name: "settings"
    label: "إعدادات الموقع"
    files:
            - label: "الإعدادات"
        name: "general"
        file: "content/settings.json"
        fields:
                    - {label: "العنوان", name: "title", widget: "string"}
                    - {label: "من نحن", name: "about", widget: "text"}
                    - {label: "واتساب", name: "whatsapp", widget: "string"}
                    - {label: "سعر طبربور", name: "price_tabarbour", widget: "number"}
